build 1.3-alpine:
  extends: .build
  variables:
    VERSION: "1.3-alpine"
    TAGS: "${VERSION}-dev"
    RELEASE_DATE: 2018-12

test 1.3-alpine:
  extends: .test
  variables:
    VERSION: "1.3-alpine"
  only:
    changes:
    - 1.3-alpine/*