
build 1.3-alpine:
  extends: .build
  variables:
    FOLDER: "1.3-alpine"
    VERSION: "$FOLDER"
    TAGS: "${FOLDER}-dev"
    RELEASE_DATE: 2018-12

test 1.3-alpine:
  extends: .test
  variables:
    FOLDER: "1.3-alpine"
    VERSION: "$FOLDER"
    TAGS: "${FOLDER}-dev"
    RELEASE_DATE: 2018-12
  only:
    changes:
    - 1.3-alpine/*