variables:
    VERSION: "1.3-alpine"
    TAGS: "${VERSION}-dev"
    RELEASE_DATE: 2018-12

build 1.3-alpine:
  extends: .build

test 1.3-alpine:
  extends: .test
  only:
    changes:
    - 1.3-alpine/*