variables:
  VERSION: "1.6-alpine"
  TAGS: "$VERSION-dev latest-dev 1-dev"
  RELEASE_DATE: 2019-06
  
build 1.6-alpine:
  extends: .build

test 1.6-alpine:
  extends: .test
  only:
    changes:
    - 1.6-alpine/*