build 1.6-alpine:
  extends: .build
  variables:
    VERSION: "1.6-alpine"
    RELEASE_DATE: 2019-06
    TAGS: "$VERSION-dev latest-dev 1-dev"

test 1.6-alpine:
  extends: .test
  variables:
    VERSION: "1.6-alpine"
  only:
    changes:
    - 1.6-alpine/*