
build 1.0-alpine:
  extends: .build
  variables:
    FOLDER: "1.0-alpine"
    VERSION: "$FOLDER"
    TAGS: "${FOLDER}-dev 1.0.0-alpine-dev"
    RELEASE_DATE: 2018-11
  
test 1.0-alpine:
  extends: .test
  variables:
    FOLDER: "1.0-alpine"
    VERSION: "$FOLDER"
    TAGS: "${FOLDER}-dev 1.0.0-alpine-dev"
    RELEASE_DATE: 2018-11
  only:
    changes:
    - 1.0-alpine/*