
build 1.1-alpine:
  extends: .build
  variables:
    FOLDER: "1.1-alpine"
    VERSION: "$FOLDER"
    TAGS: "${FOLDER}-dev 1.0.1-alpine-dev"
    RELEASE_DATE: 2018-11

test 1.1-alpine:
  extends: .test
  variables:
    FOLDER: "1.1-alpine"
    VERSION: "$FOLDER"
    TAGS: "${FOLDER}-dev 1.0.1-alpine-dev"
    RELEASE_DATE: 2018-11
  only:
    changes:
    - 1.1-alpine/*