variables:
    VERSION: "1.1-alpine"
    TAGS: "${VERSION}-dev 1.0.1-alpine-dev"
    RELEASE_DATE: 2018-11

build 1.1-alpine:
  extends: .build

test 1.1-alpine:
  extends: .test
  only:
    changes:
    - 1.1-alpine/*